var lang = {
	"ko" : {
		// 이벤트
		fire : "화재",
		falldown : "쓰러짐",
		flood : "침수",
		glove : "장갑미착용",
		invasion : "침입",
		leak : "누수",
		loitering : "배회",
		handaction : "수신호",
		spin : "약품미투입",
		cmtank : "약품탱크누액",
		outtank : "옥외탱크누액",
		overflow : "배출수월류",
		
		kwater_fire_detection : "화재",
		kwater_falldown_detection : "쓰러짐",
		kwater_flood_detection : "침수",
		kwater_glove_detection : "장갑미착용",
		kwater_invasion_detection : "침입",
		kwater_leak_detection : "누수",
		kwater_loitering_detection : "배회",
		kwater_handaction_detection : "수신호",
		kwater_spin_detection : "약품미투입",
		kwater_cmtank_detection : "약품탱크누액",
		kwater_outtank_detection : "옥외탱크누액",
		kwater_overflow : "배출수월류",

		화재 : "화재",
		쓰러짐 : "쓰러짐",
		침수 : "침수",
		장갑미착용 : "장갑미착용",
		침입 : "침입",
		누수 : "누수",
		배회 : "배회",
		수신호 : "수신호",
		약품미투입 : "약품미투입",
		
		// 이벤트 소스
		지능형안전관리시스템 : "지능형안전관리시스템",
		SCADA : "스카다", 
		
		// 날짜
		year : "년 ",
		month : "월 ",
		day : "일 ",
		hour : "시 ",
		minute : "분 ",
		second : "초",
		date : "요일",
		monday : "월요일",
		mon : "월",
		tuesday : "화요일",
		tue : "화",
		wednesday : "수요일",
		web : "수",
		thursday : "목요일",
		thu : "목",
		friday : "금요일",
		fri : "금",
		saturday : "토요일",
		sat : "토",
		sunday : "일요일",
		sun : "일",
		
		/**** 공통 ****/
		event_source : "이벤트 소스",
		device_title : "장치 이름",
		device_ip : "IP/DDNS",
		channel : "채널",
		event_info : "이벤트 정보",
		popup : "팝업",
		event_name : "이벤트",
		action : "동작",
		event_time : "발생 시간",
		run : "실행",
		cancel : "취소",
		delete_data : "삭제",
		display : "보기",
		reject : "무시",
		move : "이동",
		noImage : "이미지가 없습니다.",
		
		user_id : "아이디",
		user_name : "이름",
		user_phone : "전화번호",
		user_tokken : "라인 토큰",
		user_email : "이메일",
		user_logindate : "마지막 로그인 날짜",
		user_joindate : "가입일",
		user_isUse : "탈퇴 여부",
		user_isadmin : "등급",
		user_level : "레벨",
		more : "더보기",
		user_count : "유저 수",
		add : "추가",
		
		idx : "번호",
		device_type : "장치 종류",
		device_channel : "채널",
		device_model_name : "모델명",
		device_web_port : "포트",
		device_isconnect : "연결 상태",
		device_login_id : "사용자",
		device_mac : "MAC 주소",
		modify : "수정",
		research : "재검색",
		
		questionModification : "수정하시겠습니까?",
		questionDelete : "정말 삭제하시겠습니까?",
		questionSave : "저장하시겠습니까?",
		completeModification : "수정이 완료되었습니다.",
		completeDelete : "삭제가 완료되었습니다.",
		completeResigtration : "등록이 완료되었습니다.",
		completeSave : "저장이 완료되었습니다.",
		failedSave : "저장이 실패했습니다.",
		
		admin : "관리자",
		user : "사용자",
		
		enterName : "이름을 입력하세요.",
		enterPhone : "전화번호를 입력하세요.",
		enterId : "아이디를 입력하세요.",
		enterPassword : "비밀번호를 입력하세요.",
		enterEmail : "이메일을 입력하세요.",
		enterTokken : "토큰을 입력하세요.",
		enterDeviceTitle : "장치 이름을 입력해주세요.",
		enterIPDDNS : "IP/DDNS를 입력해주세요.",
		enterPort : "포트를 입력해주세요.",
		enterRTSP : "RTSP를 입력해주세요.",
		enterSpeakerName : "스피커 이름을 입력해주세요." ,
		enterSpeakerIP : "스피커 IP를 입력해주세요.",
		enterSpeakerPort : "스피커 Port를 입력해주세요.",
		enterSpeakerID : "스피커 ID를 입력해주세요.",
		enterSpeakerPassword : "스피커 비밀번호를 입력해주세요.",
		
		checkDuplicate : "중복체크를 해주세요.",
		wrongIDorPassword : "ID 또는 비밀번호가 틀립니다.",
		specifyNewPassword : "새로운 비밀번호를 지정해주십시오.",
		setSensitivity : "민감도를 설정해주세요.",
		setHoldingTime : "유지 시간을 설정해주세요.",
		setChannel : "채널을 선택해야 합니다.",
		setDeviceTitle : "장치 이름을 선택해주세요.",
		setEvent : "받으실 이벤트를 설정해주세요.",
		setEventAction : "동작을 선택해주세요.",
		
		setPreset : "프리셋을 선택해주세요.",
		setSpeaker : "스피커를 선택해주세요.",
		
		welcome : "환영합니다, ",
		sir : " 님.",
		
		success : "성공",
		error : "오류",
		errorLogin : "로그인 에러",
		errorCountExceeded : "ipc 갯수 초과",
		
		notAvailable : "사용 불가능",
		available : "사용 가능",
		
		unauthorizedRequest : "인증되지 않은 요청",
		invalidAccess : "잘못된 접근",
		serverError : "서버 오류로 인한 실패",
		overTimeError : "시간이 지남에 따라 처리되거나 중지됨",
		
		on : "켜기",
		off : "끄기",
		
		save : "저장",
		selectAll : "전체 선택",
		clearAll : "전체 지우기",

		alarm : "알람",
		popUp : "팝업",
		preset : "프리셋",
		sms : "SMS(SCADA)",
		speaker : "스피커",
		
		Alarm : "알람",
		PopUp : "팝업",
		Preset : "프리셋",
		Sms : "SMS(SCADA)",
		Speaker : "스피커",

		알람 : "알람",
		팝업 : "팝업",
		프리셋 : "프리셋",
		SMS : "SMS(SCADA)",
		스피커 : "스피커",
		
		speakerName : "스피커 이름",
		speakerIP : "스피커 IP",
		speakerPort : "스피커 Port",
		speakerID : "스피커 ID",
		speakerPassword : "스피커 비밀번호",
	},
	"en" : {
		// Event
		fire : "Fire",
		falldown : "Falldown",
		flood : "Flood",
		glove : "Glove",
		invasion : "Invasion",
		leak : "Leak",
		loitering : "Loitering",
		handaction : "Handaction",
		spin : "Spin",
		cmtank : "Cmtank",
		outtank : "Outtank",
		overflow : "Overflow",

		kwater_fire_detection : "Fire",
		kwater_falldown_detection : "Falldown",
		kwater_flood_detection : "Flood",
		kwater_glove_detection : "Glove",
		kwater_invasion_detection : "Invasion",
		kwater_leak_detection : "Leak",
		kwater_loitering_detection : "Loitering",
		kwater_handaction_detection : "Handaction",
		kwater_spin_detection : "Spin",
		kwater_cmtank_leak : "Cmtank",
		kwater_outtank_leak : "Outtank",
		kwater_overflow : "Overflow",
		
		Fire : "화재",
		Falldown : "쓰러짐",
		Flood : "침수",
		Glove : "장갑미착용",
		Invasion : "침입",
		Leak : "누수",
		Loitering : "배회",
		Handaction : "수신호",
		Spin : "약품미투입",
		
		// Event Source
		지능형안전관리시스템 : "KWATER",
		SCADA : "SCADA", 
		
		// Date
		year : "-",
		month : "-",
		day : " ",
		hour : ":",
		minute : ":",
		second : "",
		date : "",
		monday : "Monday",
		mon : "Mon",
		tuesday : "Tuesday",
		tue : "Tue",
		wednesday : "Wednesday",
		wed : "Wed",
		thursday : "Thursday",
		thu : "Thu",
		friday : "Friday",
		fri : "Fri",
		saturday : "Saturday",
		sat : "Sat",
		sunday : "Sunday",
		sun : "Sun",

		/**** Common ****/
		event_source : "Event Source",
		device_title : "Device Title",
		device_ip : "IP/DDNS",
		channel : "Channel",
		event_info : "Event Info",
		popup : "Popup",
		event_name : "Event Name",
		action : "Action",
		event_time : "Event Time",
		run : "Run",
		cancel : "Cancel",
		delete_data : "Delete",
		display : "display",
		reject : "reject",
		move : "move",
		noImage : "No image to display",
		
		user_id : "User ID",
		user_name : "User Name",
		user_phone : "User Phone",
		user_tokken : "Line Tokken",
		user_email : "Email",
		user_logindate : "Last Login",
		user_joindate : "Join Date",
		user_isUse : "Status",
		user_isadmin : "Grade",
		user_level : "Level",
		more : "More",
		user_count : "USER COUNT",
		add : "Add",

		idx : "No",
		device_type : "Type",
		device_channel : "Channel",
		device_model_name : "Model Name",
		device_web_port : "Port",
		device_isconnect : "Connect",
		device_login_id : "Login Id",
		device_mac : "MAC",
		modify : "Modify",
		research : "Research",

		questionModification : "Do you want to modify?",
		questionDelete : "Do you really want to delete it?",
		questionSave : "Do you want to save?",
		completeModification : "The modification has been completed.",
		completeDelete : "Delete has been completed.",
		completeResigtration : "The registration has been completed",
		completeSave : "The save has been completed",
		failedSave : "The save has been failed",
		
		admin : "Admin",
		user : "User",

		enterName : "Please enter name",
		enterPhone : "Please enter phone number",
		enterId : "Please enter ID",
		enterPassword : "Please enter password",
		enterEmail : "Please enter email",
		enterTokken : "Please enter tokken",
		enterDeviceTitle : "Please enter device title",
		enterIPDDNS : "Please enter IP/DDNS",
		enterPort : "Please enter port",
		enterRTSP : "Please enter RTSP",
		enterSpeakerName : "Please enter speaker name" ,
		enterSpeakerIP : "Please enter speaker IP",
		enterSpeakerPort : "Please enter speaker port",
		enterSpeakerID : "Please enter speaker ID",
		enterSpeakerPassword : "Please enter speaker password",
		
		enterDuplicateCheck : "Please duplicate check",
		wrongIDorPassword : "The ID or password is incorrect",
		specifyNewPassword : "Please specify a new password",
		setSensitivity : "Please set the sensitivity",
		setHoldingTime : "Please set the holding time",
		setChannel : "You must select a channel",
		setDeviceTitle : "You must select a device title",
		setEvent : "You must select a event",
		setEventAction : "You must select a event action",

		setPreset : "You must select a preset",
		setSpeaker : "You must select a speaker",
		
		welcome : "welcome, ",
		sir : "",

		success : "Success",
		error : "Error",
		errorLogin : "Login Error",
		errorCountExceeded : "Ipc count exceeded",
		
		notAvailable : "Not available",
		available : "Available",

		unauthorizedRequest : "Unauthorized request",
		invalidAccess : "Invalid access token",
		serverError : "Failure due to server error",
		overTimeError : "Processed over time or stopped",

		on : "On",
		off : "Off",

		save : "Save",
		selectAll : "Select all",
		clearAll : "Clear all",

		alarm : "Alarm",
		popUp : "PopUp",
		preset : "Preset",
		sms : "SMS(SCADA)",
		speaker : "Speaker",
		
		Alarm : "알람",
		PopUp : "팝업",
		Preset : "프리셋",
		Sms : "SMS(SCADA)",
		Speaker : "스피커",

		알람 : "Alarm",
		팝업 : "PopUp",
		프리셋 : "Preset",
		SMS : "SMS(SCADA)",
		스피커 : "Speaker",

		speakerName : "Speaker name",
		speakerIP : "Speaker IP",
		speakerPort : "Speaker port",
		speakerID : "Speaker ID",
		speakerPassword : "Speaker password",
	}
}
function getLanguage() {
    return navigator.language || navigator.userLanguage;
}
function getTranslate(tag) {
	return eval('lang.' + getLanguage().substring(0, 2) + '.' + tag);
}