var lang = {
	"ko" : {
		// 이벤트
		fire : "화재",
		falldown : "쓰러짐",
		flood : "침수",
		glove : "장갑미착용",
		invasion : "침입",
		leak : "누수",
		loitering : "배회",
		handaction : "수신호",
		spin : "약품미투입",
		cmtank : "약품탱크누액",
		outtank : "옥외탱크누액",
		overflow : "배출수월류",
		
		// 이벤트 소스
		지능형안전관리시스템 : "지능형안전관리시스템",
		SCADA : "스카다", 
		
		// 날짜
		year : "년 ",
		month : "월 ",
		day : "일 ",
		hour : "시 ",
		minute : "분 ",
		second : "초",
		date : "요일",
		monday : "월요일",
		mon : "월",
		tuesday : "화요일",
		tue : "화",
		wednesday : "수요일",
		web : "수",
		thursday : "목요일",
		thu : "목",
		friday : "금요일",
		fri : "금",
		saturday : "토요일",
		sat : "토",
		sunday : "일요일",
		sun : "일",
		
		/**** 공통 ****/
		event_source : "이벤트 소스",
		device_title : "장치 이름",
		device_ip : "IP/DDNS",
		channel : "채널",
		event_info : "이벤트 정보",
		popup : "팝업",
		event_name : "이벤트",
		action : "동작",
		event_time : "발생 시간",
		run : "실행",
		cancel : "취소",
		delete_data : "삭제",
		display : "보기",
		reject : "무시",
		move : "이동",
		noImage : "이미지가 없습니다.",
		
		user_id : "아이디",
		user_name : "이름",
		user_phone : "전화번호",
		user_tokken : "라인 토큰",
		user_email : "이메일",
		user_logindate : "마지막 로그인 날짜",
		user_joindate : "가입일",
		user_isUse : "탈퇴 여부",
		user_isadmin : "등급",
		user_level : "레벨",
		more : "더보기",
		user_count : "유저 수",
		add : "추가",
		
		idx : "번호",
		device_type : "장치 종류",
		device_channel : "채널",
		device_model_name : "모델명",
		device_web_port : "포트",
		device_isconnect : "연결 상태",
		device_login_id : "사용자",
		
		수정하시겠습니까 : "수정하시겠습니까?",
		수정이완료되었습니다 : "수정이 완료되었습니다.",
		정말삭제하시겠습니까 : "정말 삭제하시겠습니까?",
		삭제가완료되었습니다 : "삭제가 완료되었습니다."
	},
	"en" : {
		// Event
		fire : "Fire",
		falldown : "Falldown",
		flood : "Flood",
		glove : "Glove",
		invasion : "Invasion",
		leak : "Leak",
		loitering : "Loitering",
		handaction : "Handaction",
		spin : "Spin",
		cmtank : "Cmtank",
		outtank : "Outtank",
		overflow : "Overflow",

		// Event Source
		지능형안전관리시스템 : "KWATER",
		SCADA : "SCADA", 
		
		// Date
		year : "-",
		month : "-",
		day : " ",
		hour : ":",
		minute : ":",
		second : "",
		date : "",
		monday : "Monday",
		mon : "Mon",
		tuesday : "Tuesday",
		tue : "Tue",
		wednesday : "Wednesday",
		wed : "Wed",
		thursday : "Thursday",
		thu : "Thu",
		friday : "Friday",
		fri : "Fri",
		saturday : "Saturday",
		sat : "Sat",
		sunday : "Sunday",
		sun : "Sun",

		/**** Common ****/
		event_source : "Event Source",
		device_title : "Device Title",
		device_ip : "IP/DDNS",
		channel : "Channel",
		event_info : "Event Info",
		popup : "Popup",
		event_name : "Event Name",
		action : "Action",
		event_time : "Event Time",
		run : "Run",
		cancel : "Cancel",
		delete_data : "Delete",
		display : "display",
		reject : "reject",
		move : "move",
		noImage : "No image to display",
		
		user_id : "User ID",
		user_name : "User Name",
		user_phone : "User Phone",
		user_tokken : "Line Tokken",
		user_email : "Email",
		user_logindate : "Last Login",
		user_joindate : "Join Date",
		user_isUse : "Status",
		user_isadmin : "Grade",
		user_level : "Level",
		more : "More",
		user_count : "USER COUNT",
		add : "Add",

		idx : "No",
		device_type : "Type",
		device_channel : "Channel",
		device_model_name : "Model Name",
		device_web_port : "Port",
		device_isconnect : "Connect",
		device_login_id : "Login Id",

		수정하시겠습니까 : "Do you want to modify?",
		수정이완료되었습니다 : "The modification has been completed.",
		정말삭제하시겠습니까 : "Do you really want to delete it?",
		삭제가완료되었습니다 : "Delete has been completed."
	}
}
function getLanguage() {
    return navigator.language || navigator.userLanguage;
}
function getTranslate(tag) {
	return eval('lang.' + getLanguage().substring(0, 2) + '.' + tag);
}